module.exports = Object.freeze({
    STATUS_OK: 'OK',
    UPDATE_LIST: 'UPDATE_LIST',
    DISPLAY_INPUT_FIELD: 'DISPLAY_INPUT_FIELD',
    HOME_PAGE_LOADED: 'HOME_PAGE_LOADED',

    ADD: 'add',
    REMOVE: 'remove',
    UPDATE: 'update',
    
    GET_TASKS: 'GET_TASKS',
    ADD_TASK: 'ADD_TASK',
    TOGGLE_TASK: 'TOGGLE_TASK',
    COMPLETE_TASK: 'COMPLETE_TASK',
    DELETE_TASK: 'DELETE_TASK'
})